spring:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop

    datasource:
        url: jdbc:mysql://localhost:3306/spring_boot
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: root

    profiles:
        active: test
db:
    email: abdulmusavveeralji@gmail.com
    password: "@gmail.com"

management:
    endpoints:
        web:
            exposure:
                include: "*"
            base-path: "/details"
